
--1--
SELECT NAME, SALARY, DEPARTMENTNAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE SALARY > 50000;

--2--
SELECT FIRSTNAME, LASTNAME, ORDERDATE
FROM CUSTOMERS C
JOIN ORDERS O
ON O.CUSTOMERID = C.CUSTOMERID
WHERE YEAR(ORDERDATE) = 2023;

--3--
SELECT NAME, DEPARTMENTNAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON D.DEPARTMENTID = E.DEPARTMENTID;

--4--
SELECT SUPPLIERNAME, PRODUCTNAME
FROM PRODUCTS P
RIGHT JOIN SUPPLIERS S
ON S.SUPPLIERID = P.SUPPLIERID

--5--
SELECT O.ORDERID, ORDERDATE, PAYMENTDATE, AMOUNT
FROM ORDERS O
FULL OUTER JOIN PAYMENTS P
ON P.ORDERID = O.ORDERID;

--6--
SELECT 
	E1.NAME AS Name,
	E2.NAME AS Manager_name
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.EMPLOYEEID = E2.MANAGERID;

--7--
SELECT S.NAME, C.COURSENAME
FROM STUDENTS S
JOIN ENROLLMENTS E
ON E.STUDENTID = S.STUDENTID
JOIN  COURSES C
ON C.COURSEID = E.COURSEID
WHERE COURSENAME = 'MATH 101';

--8--
SELECT FIRSTNAME, LASTNAME, QUANTITY
FROM CUSTOMERS C
JOIN ORDERS O
ON O.CUSTOMERID = C.CUSTOMERID
WHERE QUANTITY > 3;

--9--
SELECT NAME, DEPARTMENTNAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE DEPARTMENTNAME = 'HUMAN RESOURCES';

--10--
SELECT D.DEPARTMENTNAME, COUNT(EMPLOYEEID) AS EMPLOYEE_COUNT
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME 
HAVING COUNT(E.EMPLOYEEID) > 10;

--11--
SELECT P.PRODUCTID, PRODUCTNAME
FROM PRODUCTS P
LEFT JOIN SALES S
ON P.PRODUCTID = S.PRODUCTID;

--12--
SELECT FIRSTNAME, LASTNAME, COUNT(ORDERID) AS TOTAL_ORDERS
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY FIRSTNAME, LASTNAME;

--13--
SELECT NAME AS EMPLOYEENAME, DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENTID = E.DEPARTMENTID;

--14--
SELECT  E1.NAME AS EMPLOYEE1, 
		E2.NAME AS EMPLOYEE2,
		E1.MANAGERID
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.MANAGERID = E2.MANAGERID
AND E1.EMPLOYEEID < E2.EMPLOYEEID;

--15--
SELECT ORDERID, ORDERDATE, FIRSTNAME, LASTNAME
FROM CUSTOMERS C
JOIN ORDERS O
ON O.CUSTOMERID = C.CUSTOMERID 
WHERE YEAR(ORDERDATE) = 2022;

--16--
SELECT NAME AS EMPLOYEENAME, SALARY, DEPARTMENTNAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'SALES'
		AND SALARY > 60000;

--17--
SELECT O.ORDERID ORDERDATE, PAYMENTDATE, AMOUNT
FROM ORDERS O
INNER JOIN PAYMENTS P
ON P.ORDERID = O.ORDERID;

--18--
SELECT P.PRODUCTID, PRODUCTNAME
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON O.PRODUCTID = P.PRODUCTID;

--19--
SELECT NAME AS EMPLOYEENAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

--20--
SELECT O.ORDERID, ORDERDATE
FROM ORDERS O
LEFT JOIN PAYMENTS P
ON P.ORDERID = O.ORDERID
WHERE YEAR(ORDERDATE) < 2022;

--21--
SELECT PRODUCTID, PRODUCTNAME
FROM PRODUCTS P
LEFT JOIN CATEGORIES C
ON C.CATEGORYNAME = P.CATEGORY;

--22--
SELECT E1.NAME AS EMPLOYEE1, E2.NAME AS EMPLOYEE2, E1.MANAGERID, E1.SALARY
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.MANAGERID = E2.MANAGERID
	AND E1.EMPLOYEEID <> E2.EMPLOYEEID
WHERE E1.SALARY > 60000;

--23--
SELECT NAME AS EMPLOYEENAME, DEPARTMENTNAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE NAME LIKE 'M%';

--24--
SELECT SALEID, PRODUCTNAME, SALEAMOUNT
FROM PRODUCTS P
JOIN SALES S
ON S.PRODUCTID = P.PRODUCTID
WHERE SALEAMOUNT > 500;

--25--
SELECT S.STUDENTID, NAME AS STUDENTNAME
FROM STUDENTS S
JOIN ENROLLMENTS E
ON E.STUDENTID = S.STUDENTID 
JOIN COURSES C
ON C.COURSEID = E.COURSEID
WHERE C.COURSENAME <> 'MATH 101';

--26--
SELECT O.ORDERID, ORDERDATE, PAYMENTID
FROM ORDERS O
LEFT JOIN PAYMENTS P
ON P.ORDERID = P.ORDERID;

--27--
SELECT PRODUCTID, PRODUCTNAME, CATEGORY AS CATEGORYNAME
FROM PRODUCTS P
JOIN CATEGORIES C
ON C.CATEGORYNAME = P.CATEGORY
WHERE CATEGORY IN ('ELECTRONICS', 'FURNITURE');

