--1--
SELECT PRODUCTNAME, SUPPLIERNAME
FROM PRODUCTS P
CROSS JOIN SUPPLIERS S;
--2--
SELECT NAME, DEPARTMENTNAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;
--3--
SELECT PRODUCTNAME, SUPPLIERNAME
FROM PRODUCTS P
JOIN SUPPLIERS S
ON P.SUPPLIERID = S.SUPPLIERID;

--4--
SELECT ORDERID, FIRSTNAME, LASTNAME
FROM ORDERS O
JOIN CUSTOMERS C
ON C.CUSTOMERID = O.CUSTOMERID;

--5--
SELECT NAME, COURSENAME
FROM STUDENTS S
CROSS JOIN ENROLLMENTS E
CROSS JOIN COURSES C;

--6--
SELECT OrderID, ProductName
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

--7--
SELECT NAME, DEPARTMENTNAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

--8--
SELECT NAME, COURSEID
FROM STUDENTS S
JOIN ENROLLMENTS E
ON S.STUDENTID = E.STUDENTID;

--9--
SELECT * 
FROM ORDERS O
JOIN PAYMENTS P
ON P.ORDERID = O.ORDERID;

--10--
SELECT *
FROM ORDERS O
JOIN PRODUCTS P
ON P.PRODUCTID = O.PRODUCTID
WHERE P.PRICE > 100;

--11--
SELECT NAME, DEPARTMENTNAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON D.DEPARTMENTID <> E.DEPARTMENTID;

--12--
SELECT *
FROM ORDERS O
JOIN PRODUCTS P
ON P.PRODUCTID = O.PRODUCTID
WHERE O.QUANTITY > P.STOCKQUANTITY;

--13--
SELECT FIRSTNAME, LASTNAME, PRODUCTID
FROM SALES S
JOIN CUSTOMERS C
ON C.CUSTOMERID = S.CUSTOMERID
WHERE SALEAMOUNT >= 50

--14--
SELECT NAME, COURSENAME
FROM STUDENTS S
JOIN ENROLLMENTS E
	ON E.STUDENTID = S.STUDENTID
JOIN COURSES C
	ON C.COURSEID =E.COURSEID;

--15--
SELECT PRODUCTNAME, SUPPLIERNAME
FROM SUPPLIERS S
JOIN PRODUCTS P
ON P.SUPPLIERID = S.SUPPLIERID
WHERE S.SUPPLIERNAME LIKE 'Tech%';

--16--
SELECT *
FROM ORDERS O
JOIN PAYMENTS P
ON P.ORDERID = O.ORDERID
WHERE P.AMOUNT < O.TOTALAMOUNT;

--17--
SELECT E1.Name AS Name, E1.Salary,
E2.Name AS Manager, E2.Salary AS Manager_Salary
FROM Employees E1
JOIN Employees E2 ON E1.ManagerID = E2.EmployeeID
WHERE E1.Salary > E1.Salary;

--18--
SELECT *
FROM PRODUCTS P
JOIN CATEGORIES C
ON P.CATEGORY = C.CATEGORYNAME
WHERE P.Category IN ('Electronics', 'Furniture');

--19--
SELECT *
FROM SALES S 
JOIN CUSTOMERS C
ON C.CUSTOMERID =  S.CUSTOMERID
WHERE COUNTRY = 'USA';

--20--
SELECT *
FROM ORDERS O
JOIN CUSTOMERS C
ON C.CUSTOMERID = O.CUSTOMERID
WHERE COUNTRY = 'GERMANY';
