--1--
SELECT MIN(PRICE) AS min_price 
FROM PRODUCTS;

--2--
SELECT MAX(SALARY) AS max_salary
FROM EMPLOYEES;

--3--
SELECT COUNT(*)
FROM CUSTOMERS;

--4--
SELECT COUNT(DISTINCT CATEGORY) AS unique_category
FROM PRODUCTS;

--5--
SELECT SUM(SALEAMOUNT) 
FROM SALES
WHERE PRODUCTID = 7;

--6--
SELECT AVG(AGE) AS avergae_age
FROM EMPLOYEES;

--7--
SELECT DepartmentName, COUNT(*) 
FROM  EMPLOYEES
GROUP BY DepartmentName;

--8--
SELECT CATEGORY, MIN(PRICE) AS min_price, MAX(PRICE) AS max_price
FROM Products
GROUP BY Category;

--9--
SELECT CUSTOMERID, SUM(SALEAMOUNT) AS sales_per_customer
FROM Sales
GROUP BY CUSTOMERID;

--10--
SELECT DEPARTMENTNAME, COUNT(EMPLOYEEID) AS Employee_per_Dep_count
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME
HAVING COUNT(EMPLOYEEID) > 5;


--11--
SELECT PRODUCTID, SUM(SALEAMOUNT) AS Total_Sales, AVG(SALEAMOUNT) AS Average_Sales
FROM Sales
GROUP BY PRODUCTID;

--12--
SELECT DEPARTMENTNAME, COUNT(EMPLOYEEID)
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME
HAVING DEPARTMENTNAME = 'HR';

--13--

SELECT DEPARTMENTNAME, MIN(SALARY) AS lowest_salary, MAX(SALARY) AS highest_salary
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME;

--14--
SELECT DEPARTMENTNAME, AVG(SALARY) AS Avg_salary_by_Department
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME;

--15--
SELECT DEPARTMENTNAME, AVG(SALARY) AS Avg_salary_by_Department, COUNT(EMPLOYEEID) AS Employee_Count_per_Department
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME;

--16--
SELECT CATEGORY, AVG(PRICE) AS Avg_Price
FROM Products
GROUP BY CATEGORY
HAVING AVG(PRICE) > 400;

--17--
SELECT YEAR(SALEDATE) AS Sales_Year, SUM(SALEAMOUNT) AS Total_Sale
FROM SALES
GROUP BY YEAR(SALEDATE);

--18--
SELECT CUSTOMERID, COUNT(ORDERID) AS Order_Count
FROM ORDERS
GROUP BY CUSTOMERID
HAVING COUNT(ORDERID) >= 3; 

--19--
SELECT DEPARTMENTNAME, SUM(SALARY) AS Total_Salary
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME
HAVING SUM(SALARY) > 500000;


--20--

SELECT PRODUCTID, AVG(SALEAMOUNT) AS Avg_Sales
FROM SALES
GROUP BY PRODUCTID
HAVING AVG(SALEAMOUNT) > 200;

--21--
SELECT CUSTOMERID, SUM(SALEAMOUNT) AS Total_Sales
FROM SALES
GROUP BY CUSTOMERID
HAVING SUM(SALEAMOUNT) > 1500;


--22--
SELECT DEPARTMENTNAME, SUM(SALARY) AS Total_Salary, AVG(SALARY) AS avg_Salary
FROM EMPLOYEES
GROUP BY DEPARTMENTNAME
HAVING AVG(SALARY) > 65000;

--23--
SELECT CUSTOMERID, MAX(TOTALAMOUNT) AS max_order_value, MIN(TOTALAMOUNT) AS min_order_value
FROM ORDERS
GROUP BY CUSTOMERID
HAVING MAX(TOTALAMOUNT) < 50;

--24--
SELECT MONTH(SALEDATE), COUNT(DISTINCT PRODUCTID), SUM(SALEAMOUNT)
FROM SALES
GROUP BY MONTH(SALEDATE)
HAVING COUNT(DISTINCT PRODUCTID) > 8;

--25--
SELECT YEAR(ORDERDATE), MIN(QUANTITY), MAX(QUANTITY)
FROM ORDERS
GROUP BY YEAR(ORDERDATE);



