--1--
SELECT CATEGORY, COUNT(PRODUCTNAME) AS number_of_products
FROM PRODUCTS
GROUP BY CATEGORY;

--2--
SELECT CATEGORY, AVG(PRICE)
FROM PRODUCTS
GROUP BY CATEGORY
HAVING CATEGORY = 'Electronics';

--3--
SELECT *
FROM CUSTOMERS
WHERE CITY LIKE 'L%';

--4--
SELECT *
FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%er';

--5--
SELECT *
FROM CUSTOMERS
WHERE COUNTRY LIKE '%A';

--6--
SELECT MAX(PRICE) AS highest_price
FROM PRODUCTS;

--7--
SELECT PRODUCTNAME, 
       IIF(STOCKQUANTITY < 30, 'Low Stock', 'Sufficient') AS stock_status
FROM PRODUCTS;

--9--
SELECT COUNTRY, COUNT(CUSTOMERID) AS number_of_customers
FROM CUSTOMERS
GROUP BY COUNTRY;

--10--
SELECT MAX(QUANTITY) AS max_quantity, MIN(QUANTITY) AS min_quantity
FROM ORDERS;

--11--
SELECT CUSTOMERID
FROM ORDERS
WHERE YEAR(ORDERDATE) = 2023
EXCEPT
SELECT CUSTOMERID
FROM INVOICES;

--12--
SELECT PRODUCTNAME
FROM PRODUCTS
UNION ALL
SELECT PRODUCTNAME
FROM Products_Discounted;

--13--
SELECT PRODUCTNAME
FROM PRODUCTS
UNION
SELECT PRODUCTNAME
FROM Products_Discounted;

--14--
SELECT YEAR(ORDERDATE) AS years, AVG(TOTALAMOUNT) AS average_amount
FROM ORDERS
GROUP BY YEAR(ORDERDATE);

--15--
SELECT PRODUCTNAME,
	CASE WHEN PRICE < 100 THEN 'Low'
		 WHEN PRICE BETWEEN 100 AND 500 THEN 'Mid'
	ELSE 'High'
	END AS price_group
FROM PRODUCTS;

--16--
SELECT DISTINCT City
FROM Customers
ORDER BY City;

--17--
SELECT PRODUCTID, SUM(SALEAMOUNT) AS total_sales
FROM SALES
GROUP BY PRODUCTID;

--18--
SELECT PRODUCTNAME
FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%OO%';

--19--
SELECT PRODUCTID
FROM PRODUCTS
INTERSECT
SELECT PRODUCTID
FROM Products_Discounted;

--20--
SELECT TOP 3 CUSTOMERID, TOTALAMOUNT AS totalspent
FROM INVOICES
ORDER BY TOTALAMOUNT DESC;

--21--
SELECT PRODUCTID, PRODUCTNAME
FROM PRODUCTS
EXCEPT
SELECT PRODUCTID, PRODUCTNAME
FROM Products_Discounted;

--22--
SELECT p.ProductName, COUNT(s.SALEAMOUNT) AS TimesSold
FROM Products p
JOIN Sales s ON p.ProductID = s.ProductID
GROUP BY p.ProductName;

--23--
SELECT TOP 5 PRODUCTID, QUANTITY
FROM ORDERS
ORDER BY QUANTITY DESC;
